release:
  title-prefix: 'v'
  initial-version: '1.0.0'
  tag-prefix: 'v'
  body-title: 'Changed'
  body-when-empty-changes: 'No changes'
  sort-by: 'note'
  sort-direction: 'ascending'
  commit-note-replacers:
    - replace-prefix: 'breaking: '
      new-prefix: ''
    - replace-prefix: 'feat: '
      new-prefix: ''
    - replace-prefix: 'feat!: '
      new-prefix: ''
    - replace-prefix: 'refactor: '
      new-prefix: ''
    - replace-prefix: 'fix: '
      new-prefix: ''
    - replace-prefix: 'docs: '
      new-prefix: ''
    - replace-prefix: 'chore: '
      new-prefix: ''
branch:
  version-branch-prefix: 'v'
  bump-version-commit-prefix: 'v'
categories:
  - title: 'Breaking Changes!'
    labels:
      - 'BreakingChange'
    commits:
      - 'BREAKING CHANGE:'
      - 'breaking:'
      - 'feat!:'
    changes-prefix: ':warning: '
  - title: 'Changes'
    labels:
      - 'Feature'
    commits:
      - 'feat:'
    changes-prefix: ':gift: '
  - title: 'Changes'
    labels:
      - Refactor
    commits:
      - 'refactor:'
      - 'chore:'
    changes-prefix: ':hammer: '
  - title: 'Bug Fixes'
    labels:
      - 'Bug'
    commits:
      - 'fix:'
    changes-prefix: ':ambulance: '
  - title: 'Changes'
    labels:
      - 'Documentation'
    commits:
      - 'docs:'
    changes-prefix: ':blue_book: '
  - title: 'Dependency Updates'
    labels:
      - 'Dependencies'
    skip-label: 'Development'
    commits:
      - 'build:'
    changes-prefix: ':green_book: '
bump:
  default: 'patch'
  major:
    labels:
      - 'BreakingChange'
    commits:
      - 'BREAKING CHANGE:'
      - 'breaking:'
      - 'feat!:'
  minor:
    labels:
      - 'Feature'
    commits:
      - 'feat:'
files:
  - file-path: 'package.json'
    line: 4
